Repository safe-global/safe-ios, pull requests merged in 2020-06, with the labels that each got.

#201 gh-145 fix unit tests spoiling app database
  Multisig.xcodeproj/project.pbxproj
  Multisig/Cross-layer/App.swift
  Multisig/Data/Persistence/CoreDataProtocol.swift
  Multisig/Data/Persistence/CoreDataStack.swift
  Multisig/Logic/Models/AppSettings.swift
  Multisig/Logic/Models/Safe.swift
  Multisig/Logic/Models/Selection.swift
  Multisig/UI/App/SceneDelegate.swift
  Multisig/UI/Safe Management/Edit Safe Name/EditSafeNameView.swift
  Multisig/UI/Safe Management/Safe Selector/SafeHeaderView.swift
  Multisig/UI/Safe Management/Switch Safe/SwitchSafeView.swift
  Multisig/UI/Settings/Get In Touch/EmailSupportViewController.swift
  MultisigTests/Data/Persistence/CoreDataTestCase.swift
  MultisigTests/Data/Persistence/TestCoreDataStack.swift
  MultisigTests/Logic/Models/AppSettingsTests.swift
  MultisigTests/Logic/Models/SafeTests.swift
Labels: bug

#236 Gh 95 tracking
  Multisig.xcodeproj/project.pbxproj
  Multisig/Cross-layer/Analytics/ConsoleTracker.swift
  Multisig/Cross-layer/Analytics/CrashlyticsTrackingHandler.swift
  Multisig/Cross-layer/Analytics/FirebaseTrackingHandler.swift
  Multisig/Cross-layer/Analytics/Tracker.swift
  Multisig/Cross-layer/Analytics/TrackingEvent.swift
  Multisig/Cross-layer/Analytics/View+Tracking.swift
  Multisig/Cross-layer/Configuration/Config.Example.xcconfig
  Multisig/Cross-layer/Logger/LogService.swift
  Multisig/Info.plist
  Multisig/Logic/Models/Safe.swift
  Multisig/UI/App/AppDelegate.swift
  Multisig/UI/Assets/AssetsView.swift
  Multisig/UI/Assets/BalancesView.swift
  Multisig/UI/ENS/EnterENSNameView.swift
  Multisig/UI/Onboarding/LaunchView.swift
  Multisig/UI/Safe Management/Edit Safe Name/EditSafeNameView.swift
  Multisig/UI/Safe Management/Load Safe/EnterSafeAddress/EnterSafeAddressView.swift
  Multisig/UI/Safe Management/Load Safe/EnterSafeName/EnterSafeNameView.swift
  Multisig/UI/Safe Management/Safe Info/SafeInfoView.swift
  Multisig/UI/Safe Management/Switch Safe/SwitchSafeView.swift
  Multisig/UI/Settings/App Settings/AdvancedAppSettings.swift
  Multisig/UI/Settings/App Settings/BasicAppSettingsView.swift
  Multisig/UI/Settings/Get In Touch/GetInTouchView.swift
  Multisig/UI/Settings/Safe Settings/AdvancedSafeSettingsView.swift
  Multisig/UI/Settings/Safe Settings/BasicSafeSettingsView.swift
  Multisig/UI/Settings/Safe Settings/SafeSettingsView.swift
  Multisig/UI/Transactions/TransactionDetails/AdvancedTransactionDetailsView.swift
  Multisig/UI/Transactions/TransactionDetails/TransactionDetailsView.swift
  Multisig/UI/Transactions/TransactionsList/TransactionsContentView.swift
  Multisig/UI/Transactions/TransactionsList/TransactionsView.swift
  Multisig/UI/UI Library/QRCodeScanner/QRCodeScannerViewController.swift
  MultisigTests/Cross-layer/Analytics/TrackerTests.swift
  MultisigTests/Cross-layer/Logger/LogServiceTests.swift
Labels: enhancement

#259 gh-249 Fix issue
  Multisig/UI/Transactions/TransactionHeaderView/SettingsChangeTransactionHeaderView/SettingsChangeTransactionDetailsHeaderView.swift
Labels: bug

#314 gh-294 generalise loadable views
  Multisig.xcodeproj/project.pbxproj
  Multisig/Assets.xcassets/ico-server-error.imageset/Contents.json
  Multisig/Assets.xcassets/ico-server-error.imageset/serverError.pdf
  Multisig/UI/Assets/AssetsView.swift
  Multisig/UI/Assets/BalancesView.swift
  Multisig/UI/Assets/BalancesViewModel.swift
  Multisig/UI/Settings/Safe Settings/BasicSafeSettingsView.swift
  Multisig/UI/Settings/Safe Settings/LoadableSafeSettingsView.swift
  Multisig/UI/Settings/Safe Settings/SafeSettingsView.swift
  Multisig/UI/Settings/Safe Settings/SafeSettingsViewModel.swift
  Multisig/UI/Transactions/TransactionsList/TransactionListView.swift
  Multisig/UI/Transactions/TransactionsList/TransactionsView.swift
  Multisig/UI/Transactions/TransactionsList/TransactionsViewModel.swift
  Multisig/UI/UI Library/LoadableView.swift
  Multisig/UI/UI Library/Text/TitleText.swift
Labels: technical debt
